name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - windows-2019
        d:
          - "ldc-1.28.0"
        clang:
          - 12.0.0
        clang_major:
          - 12
        meson:
          - 0.60.1
        ninja:
          - 1.10.2
        include:
          - os: ubuntu-20.04
            d: dmd-2.098.0
            clang: 12.0.0
            clang_major: 12
            meson: 0.60.1
            ninja: 1.10.2
          - os: macos-10.15
            d: ldc-1.28.0
            clang: 11.0.0
            clang_major: 11 # uses clang11, in which libclang is built for macos-10.15
            meson: 0.60.1
            ninja: 1.10.2
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Cache
      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.dub
            ~/AppData/Local/dub
            ./src/*/build/*.lib
            ./src/*/build/*.a
            ./.dub
            ~/llvm
            ./**/download-cache
            ~/.cache/pip
            ~/AppData/Local/pip/cache
          key: "d-tree-sitter-OS:${{ matrix.os }}-D:${{ matrix.d }}-Clang:${{ matrix.clang }}-${{ matrix.meson }}-${{ matrix.ninja }}-${{ hashFiles('./dub.sdl') }}-${{ hashFiles('./src/d_tree_sitter/tree_sitter/tree-sitter-version.txt') }}"
          restore-keys: |
            "d-tree-sitter-OS:${{ matrix.os }}-D:${{ matrix.d }}-Clang:${{ matrix.clang }}"

      # Setup compilers and tools
      - name: Setup D
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.d }}

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          meson: ${{ matrix.meson }}
          ninja: ${{ matrix.ninja }}

      - name: Setup LLVM
        if: "!${{ steps.cache.outputs.cache-hit }}"
        uses: aminya/setup-cpp@v1
        with:
          llvm: ${{ matrix.clang }}

      - name: Linux - link libclang.so
        if: contains(matrix.os, 'ubuntu')
        run: sudo ln -s libclang-${{ matrix.clang_major }}.so.1 /lib/x86_64-linux-gnu/libclang.so
        working-directory: ${{ env.LLVM_PATH }}/lib

      - name: Build
        run: dub build
        env:
          DUB_BUILD_TYPE: debug

      - name: Lint
        run: dub lint
